function TwofaVerificationPage() {
  return (
    <form className="w-96 space-y-6 rounded-lg p-4 text-sm shadow-[0px_0px_10px_0px_var(--color-neutral-500)] ring-[0.5px] ring-neutral-900">
      <h1 className="text-center text-lg font-medium">
        Two-Factor Authentication
      </h1>
      <p className="my-3 px-1.5 text-sm">
        Enter a 6-digit login code generated by an authentication app
      </p>
      <div className="mx-auto my-6 grid w-[95%] grid-cols-6 grid-rows-1 gap-2">
        <input
          type="number"
          className="w-full rounded-md p-1.5 text-center ring-[0.5px] ring-neutral-900 focus-visible:shadow-[0px_0px_8px_0px_var(--color-neutral-700)] focus-visible:outline-hidden"
        />
        <input
          type="number"
          className="w-full rounded-md p-1.5 text-center ring-[0.5px] ring-neutral-900 focus-visible:shadow-[0px_0px_8px_0px_var(--color-neutral-700)] focus-visible:outline-hidden"
        />
        <input
          type="number"
          className="w-full rounded-md p-1.5 text-center ring-[0.5px] ring-neutral-900 focus-visible:shadow-[0px_0px_8px_0px_var(--color-neutral-700)] focus-visible:outline-hidden"
        />
        <input
          type="number"
          className="w-full rounded-md p-1.5 text-center ring-[0.5px] ring-neutral-900 focus-visible:shadow-[0px_0px_8px_0px_var(--color-neutral-700)] focus-visible:outline-hidden"
        />
        <input
          type="number"
          className="w-full rounded-md p-1.5 text-center ring-[0.5px] ring-neutral-900 focus-visible:shadow-[0px_0px_8px_0px_var(--color-neutral-700)] focus-visible:outline-hidden"
        />
        <input
          type="number"
          className="w-full rounded-md p-1.5 text-center ring-[0.5px] ring-neutral-900 focus-visible:shadow-[0px_0px_8px_0px_var(--color-neutral-700)] focus-visible:outline-hidden"
        />
      </div>
      <button
        type="submit"
        className="w-full cursor-pointer rounded-md bg-neutral-500 p-2 text-white focus-visible:outline-hidden"
      >
        Verify
      </button>
    </form>
  );
}

export default TwofaVerificationPage;
